'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('product',
      [
        {
          "id": 1,
          "name": "Estátua Figura The Child Na Cadeira Baby Yoda Mandalorian",
          "slug": "estatua-figura-the-child-na-cadeira-baby-yoda-mandalorian",
          "title": "Estátua The Child Baby Yoda",
          "category": "StarWars",
          "department": "Decoração",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Prepare-se para o hiperespaço! A estrela emergente de The Mandalorian no Disney Plus é definitivamente a criança, e ela merece sua honra nesta nova estátua em escala 1/2! Sentado no banco do passageiro do Razor Crest, segurando seu botão de controle de prata favorito em sua mão, o Child será o complemento perfeito para a coleção de qualquer fã do Mandalorian. Medindo aproximadamente 30 centímetros de altura, ele vem embalado em uma caixa de janela colorida e inclui um certificado de autenticidade numerado. Desenhado por Joe Allard e esculpido por Jorge Santos Souza. Imagem meramente ilustrativa.",
          "manufacturer": "Diamond Select",
          "brand": "StarWars",
          "character": "Baby Yoda",
          "material": "resina",
          "weight": 5.62,
          "height": 37,
          "width": 25,
          "depth": 24.5,
          "fullPrice": 3000
        },
        {
          "id": 2,
          "name": "Livro StarWars: Dark Edition",
          "slug": "livro-starwars-dark-edition",
          "title": "Livro StarWars Dark Edition",
          "category": "StarWars",
          "department": "Livros, revistas e comics",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Em uma galáxia muito, muito distante, os fãs de Star Wars aguardavam por este momento inesquecível. No ano de encerramento da saga mais lendária da história do cinema, a DarkSide® Books apresenta uma nova edição de Star Wars: A Trilogia. Muito além de um fenômeno do cinema, Star Wars ditou regras na ficção científica, inspirou milhares de pessoas com a filosofia Jedi, nos levou até mundos incríveis e apresentou os personagens mais cativantes que poderiam existir no espaço. As clássicas histórias de Luke Skywalker, Han Solo, Princesa Leia, Mestre Yoda e Darth Vader vão ganhar detalhes de outra galáxia em uma nova edição que todo geek terá orgulho de exibir em sua estante. A nova capa de Star Wars: A Trilogia tem detalhes em dourado, material semelhante a couro, Leia. As páginas de guarda da nova edição também contam com um detalhe especial: elas brilham mais que um sabre de luz no escuro. No ano em que a saga Star Wars chega ao fim com Star Wars Episódio IX: A Ascensão Skywalker, a DarkSide® Books apresenta uma nova edição que faz jus a importância da saga iniciada em 1977. Em Star Wars: A Trilogia, George Lucas escreve o Episódio IV – Uma Nova Esperança, com participação de Alan Dean Foster, a partir de uma adaptação do roteiro original do longa, e mostra, pela primeira vez, o jovem Luke Skywalker aos fãs, cinco meses antes do lançamento oficial do filme. O Episódio V – O Império Contra-Ataca, escrito por Donald F. Glut, é um dos mais adorados da saga e coloca Luke diante de lados opostos da Força. “Eu jamais poderia imaginar o nível dos laços emocionais que o público havia desenvolvido com Luke como um símbolo de bondade e Vader como a personificação do mal”, declarou George Lucas tempos depois. Já o Episódio VI – O Retorno de Jedi foi escrito por James Kahn – mesmo autor de Os Goonies, lançado pela DarkSide® Books. E preparar esse capítulo final da trilogia foi um grande desafio para George Lucas, já que o roteiro apresentava muitas histórias abertas e era preciso deixar tudo muito bem amarrado para os próximos filmes. A nova edição de Star Wars: A Trilogia, da DarkSide® Books, é também uma homenagem aos atores da saga que se foram recentemente, mas serão para sempre lembrados. Carrie Fisher (Princesa Leia) e Peter Mayhew (Chewbacca) se tornaram figuras fundamentais em Star Wars e conquistaram o coração dos fãs. Para os espectadores ainda mais saudosos, Fisher aparecerá em Star Wars – Episódio IX: A Ascensão Skywalker. Cenas gravadas para o Episódio VII (2015), e até então inéditas, serão aproveitadas no novo longa e prometem emocionar a todos. A DarkSide® Books também se preocupou em lançar a nova edição de Star Wars: A Trilogia no mês mais importante para a saga: maio. Somente um verdadeiro fã de Star Wars consegue entender essa importância. No dia 4 de maio é celebrado o #MayThe4thBeWithYou, uma espécie de feriado não-oficial com milhares de comemorações e reuniões dos fãs de Star Wars pelo mundo. Ainda neste mês, no dia 25 – conhecido como o Dia da Toalha –, foram lançados no cinema os Episódios IV e VI da saga; já o Episódio V ganhou as telonas no dia 21 de maio de 1980; George Lucas comemora seu aniversário no dia 14 e outro nome marcante também celebraria neste mês: Peter Mayhew, nascido no dia 19. Os fãs de Star Wars já podem comemorar em grande estilo, com uma edição épica que será admirada até mesmo das galáxias mais distantes do universo – uma verdadeira bíblia geek, o manual que todo e qualquer mochileiro Jedi precisa ter em sua coleção.",
          "manufacturer": "Editora Darkside | George Lucas",
          "brand": "StarWars",
          "character": "StarWars",
          "material": "capa dura",
          "weight": 0.849,
          "height": 23,
          "width": 16,
          "depth": 3.8,
          "fullPrice": 63.9
        },
        {
          "id": 3,
          "name": "Funko Pop! Pride Star Wars - Stormtrooper (296)",
          "slug": "funko-pop-pride-starwars-296-stormtrooper",
          "title": "Funko Pop! Pride Stormtrooper",
          "category": "StarWars",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Decoração ou coleção?! Não precisa mais se perguntar. A linha POP! da marca americana Funko, chegou para ficar!! Com uma enorme gama de modelos dos mais variados personagens, podendo capturar toda essência de diversos mundos. De filmes, jogos, séries, animações entre outros. Confira os nossos modelos e fique tranquilo pois oferecemos apenas produtos ORIGINAIS, novos, acompanhados de notas ficais e a pronta-entrega.",
          "manufacturer": "Funko",
          "brand": "StarWars",
          "character": "Stormtrooper",
          "material": "vinil",
          "weight": 0,
          "height": 10,
          "width": 5,
          "depth": 5,
          "fullPrice": 139.9
        },
        {
          "id": 4,
          "name": "Funko Pop Star Wars 456 Darth Vader Retro Series",
          "slug": "funko-pop-pride-starwars-456-darth-vader-retro-series",
          "title": "Funko Pop! Darth Vader Retro Series",
          "category": "StarWars",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Da Coleção Retro Series, Darth Vader, como um Pop! da Funko. Tamanho aprox. 10 cm. ITENS INCLUSOS: 01 - Funko Pop Star Wars 456 Darth Vader Retro Series",
          "manufacturer": "Funko",
          "brand": "StarWars",
          "character": "Darth Vader",
          "material": "vinil",
          "weight": 0,
          "height": 10,
          "width": 5,
          "depth": 5,
          "fullPrice": 139.9
        },
        {
          "id": 5,
          "name": "Pantufa 3d Chewbacca - Star Wars Original - Solado De Borracha",
          "slug": "pantufa-3d-chewbacca-starwars-original-solado-de-borracha",
          "title": "Pantufa 3d Chewbacca - Solado De Borracha",
          "category": "StarWars",
          "department": "Calçados",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Prepare os grunhidos! A pantufa do famoso co-piloto da nave Millenium Falcon chegou com tudo, trazendo muita diversão aos seus pés, no melhor estilo Wookiee! Super peluda, confortável e com um acabamento de outro planeta, a pantufa 3D do Chewbacca é o presente que vai fazer o maior sucesso entre os jedis e os fãs da famosa série, de sucesso intergaláctico, Star Wars. Um legítimo par de pés wookies, direto de Kashyyyk, pra te salvar das noites frias e te tirar da rotina com muita ação e aventura! Produto licenciado Star Wars / Disney. Cuidados com o produto: 1) Lavar à mão. 2) Não usar alvejante. 3) Secagem ao natural. 4) Não passar e limpar à seco. Características do produto: - Solado de borracha. - Materiais: Poliéster e borracha. Tamanho: 34/36 - 25,3cm | Tamanho: 37/39 - 26,5cm | Tamanho: 40/42 - 28,5cm | Tamanho: 43/44 - 30,0cm | Tamanho: 28/30 - 22,2cm | Tamanho: 31/33 - 23,9cm | Tamanho: 34/36 - 25,3cm | Tamanho: 37/39 - 26,5cm | Tamanho: 40/42 - 28,5cm | Tamanho: 43/44 - 30,0cm | Tamanho: 45/46 - 31,5cm.",
          "manufacturer": "Ricsen",
          "brand": "StarWars",
          "character": "Chewbacca",
          "material": "pelúcia",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 170
        },
        {
          "id": 6,
          "name": "Lego Star Wars 75295 - Microfighter Millennium Falcon - 101 pçs",
          "slug": "lego-starwars-75295-microfighter-millennium-falcon-101-pcs",
          "title": "Lego Millennium Falcon 101 pçs",
          "category": "StarWars",
          "department": "Decoração",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Com 90 anos de trajetória, a Lego é um dos principais fabricantes mundiais de materiais de jogo. Para a marca, o jogo é vital no desenvolvimento de todos os meninos e meninas, pois os ajuda a prosperar num mundo complexo e desafiante. Seu principal objetivo é inspirar e desenvolver os construtores do futuro, além de gerar um impacto positivo na sociedade e no planeta. Os brinquedos da Lego oferecem a possibilidade dum descobrimento permanente, oferecendo a oportunidade mágica de criar algo novo sempre. Viaje para uma galáxia muito, muito distante com o kit Lego Star Wars. Você poderá criar suas próprias obras inspiradas nesta história e se transportar com cada um de seus personagens para o maravilhoso mundo de Stormtroopers, imperadores, Jedi, Wookiees e extraterrestres. Fácil de mover e armazenar. Sua exibição em caixa, permite que você carregue seu kit para qualquer lugar duma forma confortável e prática. É útil não só para o transporte, mas também para facilitar o armazenamento em qualquer lugar da sua casa. Uso supervisionado. Recomenda-se usá-lo a partir dos 6 anos. Por favor, supervisionar meninos e meninas para evitar acidentes.",
          "manufacturer": "Lego",
          "brand": "StarWars",
          "character": "StarWars",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 89.99
        },
        {
          "id": 7,
          "name": "Star Wars Edição De 40 Anos - 4Lom E Zuckuss - Hasbro E9925",
          "slug": "starwars-edicao-de-40-anos-4lom-e-zuckuss-asbro-e9925",
          "title": "Bonecos 4Lom E Zuckuss - StarWars",
          "category": "StarWars",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/starwars/ads-starwars-products.png",
          "description": "Quando a Kenner produziu pela primeira vez as figuras dos caçadores de recompensas 4-LOM e Zuckuss, os seus nomes acabaram saindo trocados na embalagem. Entretanto, como eles não eram citados no filme, a princípio ninguém notou. Apenas em 1989 esse equívoco foi detectado e corrigido, e finalmente Zuckuss e 4-LOM foram identificados corretamente. Esse kit com réplicas das embalagens originais, inclusive com os nomes trocados, celebra a primeira aparição destas figuras, que por tantos anos confundiu os fãs. Imagens meramente ilustrativas. Para comemorar o 40º aniversário de Star Wars: Episódio V O Império Contra-Ataca com esta variedade de figuras de ação de Star Wars The Black Series de 6 polegadas. Com requintado design e detalhes inspirados em filmes, Star Wars The Black Series têm a qualidade e o realismo que os fãs da saga Star Wars apreciam. Essas figuras de ação altamente posáveis apresentam deco inspirado no figurino do episódio V The Empire Strikes Back. (Cada um é vendido separadamente. Sujeito à disponibilidade.)",
          "manufacturer": "Hasbro",
          "brand": "StarWars",
          "character": "4LOM | Zuckuss",
          "material": "plástico",
          "weight": 0,
          "height": 15,
          "width": 0,
          "depth": 0,
          "fullPrice": 599.99
        },
        {
          "id": 8,
          "name": "Capa Anti Impacto Slim Samsung Galaxy A12 Marvel Vingadores",
          "slug": "capa-anti-impacto-slim-samsung-galaxy-a12-marvel-vingadores",
          "title": "Capa Anti Impacto Slim Samsung A12 Vingadores",
          "category": "Marvel",
          "department": "Capas para celular",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Capas 100% em TPU alemão com garantia de 6 meses contra amarelamento! Capas com impressão digital UV de alta nitidez e garantia de 1 ano contra descascamento! Compatível com carregamento Wireless/Indução/Magsafe. Não precisa remover a capa para carregar o celular! Envio imediato ou próximo dia útil para todo Brasil! Encaixe perfeito para os botões e design do seu aparelho, sem deixar folgas e nem deixar o design volumoso. Com pegada firme e botões de fácil pressionamento, mantém o aparelho sempre confortável em sua mão e seguro em superfícies escorregadias! Material com ALTO PADRÃO de qualidade! Material Flexível de fácil aplicação e absorção de impactos! Somente CAPAS ORIGINAIS GOCASE e estampas licenciadas.",
          "manufacturer": "GOCase",
          "brand": "Marvel",
          "character": "Vingadores",
          "material": "tpu",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 79.90
        },
        {
          "id": 9,
          "name": "Boneco Marvel Loki Avengers Hasbro Titan Hero Series",
          "slug": "boneco-marvel-loki-avengers-hasbro-titan-hero-series",
          "title": "Boneco Marvel Loki Titan Hero Series",
          "category": "Marvel",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "A empresa Hasbro é proprietária de diferentes marcas, brinquedos e jogos de tabuleiro. Desde 1923, ela se dedica a criar e contagiar felicidade com seus produtos. Brinquedos articulados. Ao ter marcadas as articulações, você poderá manusear e ajustar suas figuras como quiser. Com elas, você poderá criar histórias onde os personagens podem se mobilizar e ganhar vida.",
          "manufacturer": "Hasbro",
          "brand": "Marvel",
          "character": "Loki",
          "material": "plástico",
          "weight": 0,
          "height": 12,
          "width": 0,
          "depth": 0,
          "fullPrice": 129.90
        },
        {
          "id": 10,
          "name": "Marvel's Spider-Man: Miles Morales Standard Edition Sony PS5 Físico",
          "slug": "marvels-spider-man-miles-morales-standard-edition-sony-ps5-fisico",
          "title": "Marvel's Spider-Man: Miles Morales PS5",
          "category": "Marvel",
          "department": "Games",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Com este jogo Homem-Aranha, você desfrutará de horas de diversão e novos desafios que lhe permitirão melhorar como jogador.",
          "manufacturer": "Sony",
          "brand": "Marvel",
          "character": "SpiderMan",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 108
        },
        {
          "id": 11,
          "name": "Quebra-cabeça Disney Frozen 200 peças - Toyster 8033",
          "slug": "quebra-cabeca-disney-frozen-200-pecas-toyster-8033",
          "title": "Quebra-cabeça Frozen 200 pçs",
          "department": "Jogos de tabuleiro e cartas",
          "category": "Princesas",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": ".",
          "manufacturer": "Toyster",
          "brand": "Princess",
          "character": "Frozen",
          "material": "cartão",
          "weight": 0,
          "width": 30.9,
          "height": 44,
          "depth": 0,
          "fullPrice": 24.99
        },
        {
          "id": 12,
          "name": "Boneca Princesa Disney Mulan E8633 Traje Guerreira Hasbro",
          "slug": "boneca-princesa-disney-mulan-e8633-traje-guerreira-hasbro",
          "title": "Boneca Mulan Guerreira",
          "category": "Princesas",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "Uma amizade fiel. A partir de hoje, toda criança será acompanhada por alguém incondicional, capaz de transformar o mundo em um lugar encantador. Personagens inesquecíveis. Com Mulan, as experiências das crianças serão incríveis! Seu design favorece a criatividade e a imaginação.",
          "manufacturer": "Hasbro",
          "brand": "Princess",
          "character": "Mulan",
          "material": "plástico",
          "weight": 0,
          "height": 30,
          "width": 0,
          "depth": 0,
          "fullPrice": 64.77
        },
        {
          "id": 13,
          "name": "Chinelo Havaianas Slim Princesas Disney Feminina",
          "slug": "chinelo-havaianas-slim-princesas-disney-feminina",
          "title": "Chinelo Havaianas Slim Princesas",
          "category": "Princesas",
          "department": "Calçados",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "Deixe o sapatinho de cristal de lado e receba todo o conforto que só um bom par de Havaianas tem! Seja qual for a sua idade, a gente garante que a beleza clássica de cada uma das princesas da Disney que estampa este modelo vai ganhar seu coração. Era uma vez... Era uma vez uma princesa apaixonada por sapatos que ficou muito triste quando descobriu que estava condenada a usar o mesmo par para o resto de sua vida. Num passe de mágica, surgiu sua fada madrinha, que trouxe com ela um belíssimo par de Havaianas Slim Princesas. E viveu feliz para sempre! Sonho de princesa: Clássicos são eternos, e celebrar a magia que a Disney trouxe para a nossa infância é tendência atemporal. Para quem é fã da Pequena Sereia, a sandália com estampa da princesa Ariel é um verdadeiro sonho realizado! Lista de cuidados: Lave à mão com sabão neutro e uma escova macia ou na máquina de lavar. Deixe secar em um local bem ventilado e... Prontinho! Suas Havaianas ficam novinhas em folha! Tamanho: 33/34 - 21,1 ~ 22,3cm | Tamanho: 35/36 - 22,4 ~ 23,6cm | Tamanho: 37/38 - 23,7 ~ 25,0cm | Tamanho: 39/40 - 25,1 ~ 26,3 cm | Tamanho: 41/42 - 26,4 ~ 27,6 cm.",
          "manufacturer": "Havaianas",
          "brand": "Princess",
          "character": "Princesas",
          "material": "borracha",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 49.99
        },
        {
          "id": 14,
          "name": "Bicicleta Infantil Aro 16 Princesas Disney - Nathor",
          "slug": "bicicleta-infantil-aro16-princesas-disney-nathor",
          "title": "Bicicleta Infantil Aro 16 Princesas",
          "category": "Princesas",
          "department": "Bicicletas",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "Sofisticação e agilidade. Indicada para crianças a partir de 5 anos ou com altura entre 1,10m e 1,20m.Diversão e aventura com conforto e segurança!. As bicicletas aro 16” Nathor possuí modelos com aro em ABS e em alumínio.O limitador de giro evita que o guidão vire completamente, proporcionando mais segurança e preservando o freio. Para facilitar o aprendizado e a identificação do freio traseiro, a maçaneta amarela ganha destaque e indica o acionamento ideal na hora da frenagem. A regulagem de altura das rodinhas laterais permite o desenvolvimento da criança na fase de aprendizado, estimulando o equilíbrio e a autonomia. A aro 16” tem pneus com câmara, quadro em aço carbono e garrafinha.",
          "manufacturer": "Nathor",
          "brand": "Princess",
          "character": "Princesas",
          "material": "aço",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 729.90
        },
        {
          "id": 15,
          "name": "Lego Princesas 43188 Disney Casa Da Aurora Bela Adormecida",
          "slug": "lego-princesas-43188-disney-casa-da-aurora-bela-adormecida",
          "title": "Lego Princesas Casa Da Aurora Bela Adormecida",
          "category": "Princesas",
          "department": "Bicicletas",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "Com 90 anos de trajetória, a Lego é um dos principais fabricantes mundiais de materiais de jogo. Para a marca, o jogo é vital no desenvolvimento de todos os meninos e meninas, pois os ajuda a prosperar num mundo complexo e desafiante. Seu principal objetivo é inspirar e desenvolver os construtores do futuro, além de gerar um impacto positivo na sociedade e no planeta. Os brinquedos da Lego oferecem a possibilidade dum descobrimento permanente, oferecendo a oportunidade mágica de criar algo novo sempre. Viaje para uma galáxia muito, muito distante com o kit Lego Star Wars. Você poderá criar suas próprias obras inspiradas nesta história e se transportar com cada um de seus personagens para o maravilhoso mundo de Stormtroopers, imperadores, Jedi, Wookiees e extraterrestres. Fácil de mover e armazenar. Sua exibição em caixa, permite que você carregue seu kit para qualquer lugar duma forma confortável e prática. É útil não só para o transporte, mas também para facilitar o armazenamento em qualquer lugar da sua casa. Uso supervisionado. Recomenda-se usá-lo a partir dos 6 anos. Por favor, supervisionar meninos e meninas para evitar acidentes.",
          "manufacturer": "Lego",
          "brand": "Princess",
          "character": "Bela Adomercida",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 439.78
        },
        {
          "id": 16,
          "name": "Escova Elétrica Oral-B Princess Disney + 2 Pilhas AA",
          "slug": "escova-eletrica-oral-b-princesas-disney-com-2-pilhas-AA",
          "title": "Escova Elétrica Oral-B Princesas",
          "category": "Princesas",
          "department": "Higiene",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "Escova Dental Oral-B Princess Disney + 2 Pilhas AA A Escova de Dentes Elétrica Oral-B Kids Princess para crianças maiores de 3 anos combina a diversão das Princesas Disney com a limpeza suave e eficaz de uma escova de dentes Oral-B. Especialmente projetada para crianças, esta escova limpa os dentes suavemente e remove mais placa bacteriana do que uma escova manual normal, protegendo a saúde do seu filho. Além disso, sua cabeça redonda possui cerdas extra macias que protegem a gengiva dos pequenos. A escova de dentes elétrica Oral-B Kids possui um cronômetro para que as crianças escovem os dentes por dois minutos, tempo de escovação recomendado pelos dentistas, que ajudará seu filho a desenvolver bons hábitos de escovação para toda a vida. A escova é compatível com todos os refis de escovas elétricas Oral-B e possui cabo emborrachado, resistente à água e ergonômico, adaptado para as crianças. Para transformar a escovação ainda mais divertida, Oral-B recomenda o uso do aplicativo Disney Magic Timer, com adesivos, conquistas e muito mais para ajudar na saúde bucal infantil. • Projetado especificamente para limpar suavemente os dentes das crianças • Cabeça redonda especial para bocas de meninas • Filamentos extra suaves cuidam das gengivas mais delicadas • Funciona com o app Disney Magic Timer da Oral-B • Incentiva a escovagem por 2 minutos, graças ao seu cronômetro embutido e seu temporizador embutido - Contém: 1 Cabo Ergonômico 1 Refil 2 pilhas AA - Compre produtos Oral B",
          "manufacturer": "Oral-B",
          "brand": "Princess",
          "character": "Princesas",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 179.90
        },
        {
          "id": 17,
          "name": "Fichário Caderno Argolado Escolar Princesas",
          "slug": "fichario-caderno-argolado-escolar-princesas-disney",
          "title": "Fichário Argolado Princesas Disney",
          "category": "Princesas",
          "department": "Escolar",
          "productionBanner": "/images/banners/princess/banner-princess-image1-princess.jpg",
          "description": "O Fichário pequeno Disney Princesas é muito queridinho e o item perfeito para ter foco. Ideal para estimular a organização dos estudos diários e alcançar as metas e objetivos sem perder a motivação. Cheio de versatilidade ao inserir ou retirar folhas, pois as argolas articuladas abrem, possibilitando esta ação. Útil e estiloso, foi feito para arrasar! Pronto para escola ou faculdade.",
          "manufacturer": "DAC",
          "brand": "Princess",
          "character": "Princesas",
          "material": "plástico",
          "weight": 0.346,
          "height": 25.1,
          "width": 18.5,
          "depth": 4,
          "fullPrice": 99.90
        },
        {
          "id": 18,
          "name": "Caneca 3d Pantera Negra - Marvel Original",
          "slug": "caneca-3d-pantera-negra-marvel-original",
          "title": "Caneca 3d Pantera Negra Marvel",
          "category": "Marvel",
          "department": "Decoração",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Produto original Pantera Negra/ Licenciado Marvel. A caneca do príncipe de Wakanda veio para deixar seu café da manha ainda mais animado! É o presente perfeito para você garantir sua coleção de canecas, decorar seu espaço com personalidade, ou presentear quem você gosta e se fazer lembrar de forma muito especial, e muito legal para usar com a sua bebida preferida; ou para uma decoração criativa certa para fazer muito sucesso com os apaixonados pelo universo da Marvel e dos super-heróis!",
          "manufacturer": "Marvel",
          "brand": "Marvel",
          "character": "Pantera Negra",
          "material": "cerâmica",
          "weight": 0,
          "height": 11,
          "width": 9,
          "depth": 12,
          "fullPrice": 69.9
        },
        {
          "id": 19,
          "name": "Boneco Funko Pop Visão Anos 70 718 - Wandavision Marvel",
          "slug": "funko-pop-visao-anos70-718-wandavision-marvel",
          "title": "Funko Pop Visão Anos70 718 Wandavision",
          "category": "Marvel",
          "department": "Bonecos e action figures",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Direto do universo Marvel esse funko do Visão veio para deixar a sua coleção ainda mais divertida e diferente! Com um visual dos anos 70 da serie WandaVision, esse funko vem bem colorido e com muitos detalhes, além de a cabeça bobble-head, garantindo o máximo de diversão para sua coleção!",
          "manufacturer": "Funko",
          "brand": "Marvel",
          "character": "Visão",
          "material": "vinil",
          "weight": 0,
          "height": 10,
          "width": 5,
          "depth": 5,
          "fullPrice": 178.31
        },
        {
          "id": 20,
          "name": "Lego Marvel Os Eternos Emboscada Deviante 76154 - 197 pcs",
          "slug": "lego-marvel-os-eternos-emboscada-deviante-76154-197pcs",
          "title": "Lego Os Eternos Emboscada Deviante 197 pçs",
          "category": "Marvel",
          "department": "Decoração",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Com 90 anos de trajetória, a Lego é um dos principais fabricantes mundiais de materiais de jogo. Para a marca, o jogo é vital no desenvolvimento de todos os meninos e meninas, pois os ajuda a prosperar num mundo complexo e desafiante. Seu principal objetivo é inspirar e desenvolver os construtores do futuro, além de gerar um impacto positivo na sociedade e no planeta. Os brinquedos da Lego oferecem a possibilidade dum descobrimento permanente, oferecendo a oportunidade mágica de criar algo novo sempre. Viaje para uma galáxia muito, muito distante com o kit Lego Star Wars. Você poderá criar suas próprias obras inspiradas nesta história e se transportar com cada um de seus personagens para o maravilhoso mundo de Stormtroopers, imperadores, Jedi, Wookiees e extraterrestres. Fácil de mover e armazenar. Sua exibição em caixa, permite que você carregue seu kit para qualquer lugar duma forma confortável e prática. É útil não só para o transporte, mas também para facilitar o armazenamento em qualquer lugar da sua casa. Uso supervisionado. Recomenda-se usá-lo a partir dos 6 anos. Por favor, supervisionar meninos e meninas para evitar acidentes.",
          "manufacturer": "Lego",
          "brand": "Marvel",
          "character": "Os Eternos",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 249.99
        },
        {
          "id": 21,
          "name": "Toalhas umedecidas Huggies Max Clean 48 unidades",
          "slug": "toalhas-umedecidas-huggies-max-clean-48-unidades",
          "title": "Toalhas umedecidas Huggies Max Clean 48 unidades",
          "category": "Classicos",
          "department": "Higiene",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Livre de álcool. É hipoalérgica.",
          "manufacturer": "Huggies",
          "brand": "Classic",
          "character": "Mickey",
          "material": "toalha umedecida",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 17.35
        },
        {
          "id": 22,
          "name": "Cômoda Infantil 3 Gavetas Minnie Disney Fun Cabecasa",
          "slug": "comoda-infantil-3-gavetas-minnie-disney-fun-cabecasa",
          "title": "Cômoda Infantil 3 Gavetas Minnie Disney",
          "category": "Classicos",
          "department": "Decoração",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Cômoda Infantil 3 Gavetas Minnie Disney Fun CabeCasa MadeiraMadeira. Dê um toque especial ao quarto das crianças com Cômoda Infantil Minnie Disney Fun, que além de complementar a composição do quarto ainda deixa o seu ambiente mais bonito e divertido. Depois nos conte como foi a experiência de compra e como ficou seu ambiente nos comentários. Garantia : 24 Meses. Acabamento : Pintura UV. Possui Pés : 04 pés. Possui Nichos : Não. Possui Portas : Não. Escala de Brilho : Semi-Brilho. Material dos Pés : Eucalipto. Material do Fundo : MDF. Origem do Produto : Nacional. Acabamento dos Pés : Pintura. Ambiente Principal : Quarto Infantil. Material da Gaveta : MDF. Material Principal : MDF. Acabamento da Gaveta : Pintura UV. Tipo de Puxador da Gaveta : Externo. Escala de Brilho da Gaveta : Semi-Brilho. Tipo de Corrediça da Gaveta : Metálica Simples. Material do Puxador da Gaveta : Madeira Maciça. Cor Predominante : Branco. Pés Reguláveis : Não. Possui Rodízio : Não. Possui Espelhos : Não. Gaveta com Chave : Não. Sapatas Niveladoras : Não. Marca : CabeCasa MadeiraMadeira. Cor Interna : Branco. Cor do Produto : Branco/Minnie. Itens Inclusos : 1 Cômoda com 4 pés, Kit de Ferragens e Manual de Montagem. Linha ou Coleção : Disney Fun. Informações Complementares : Tampo: 30kg Gaveta: 10kg. Peso (kg) : 31.1. Altura (cm) : 86.4. Largura (cm) : 80.6. Altura dos Pés : 15. Suporta Até (kg) : 60. Profundidade (cm) : 45.2. Peso Máximo por Gaveta : 10. Informações Complementares (Novo) : Tampo: 10KgGaveta: 3Kg",
          "manufacturer": "MadeiraMadeira",
          "brand": "Classic",
          "character": "Minnie",
          "material": "madeira",
          "weight": 31.1,
          "height": 86,
          "width": 80,
          "depth": 45,
          "fullPrice": 599.9
        },
        {
          "id": 23,
          "name": "Pantufa Chinelo Solado Borracha Minnie Disney Original",
          "slug": "pantufa-chinelo-solado-borracha-minnie-disney-original",
          "title": "Pantufa Chinelo Solado Borracha Minnie",
          "category": "Classicos",
          "department": "Calçados",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "O Ratinho favorito das crianças e dos adultos veio para trazer muita magia Disney para o seu dia a dia! Perfeita para você curtir seus momentos de relaxamento, do inverno ao verão, sempre confortável e com seu parceiro favorito nos pés! Produto original Disney / Mickey Mouse. Cuidados com o produto: Temperatura máxima de lavagem a 30ºC – Processo normal. Não alvejar. Secagem mecânica temperatura mínima. Não passar. Lavagem a seco. Características do produto: Moldura com acabamento em bordado. Materiais: Borracha, poliéster e pelúcia baixa. Tamanho: 33/34/35 - 24cm | Tamanho: 36/37/38 - 26cm | Tamanho: 39/40/41 - 28cm | Tamanho: 42/43/44 - 30cm.",
          "manufacturer": "Huggies",
          "brand": "Classic",
          "character": "Mickey",
          "material": "pelúcia",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 119.9
        },
        {
          "id": 24,
          "name": "Quebra-cabeça Disney Mickey 1500 peças - GameOffice 2715",
          "slug": "quebra-cabeca-disney-mickey-15000-pecas-gameoffice-2715",
          "title": "Quebra-cabeça Mickey 1500 pçs",
          "category": "Classicos",
          "department": "Jogos de tabuleiro e cartas",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Quebra Cabeça Panorâmico Mickey Mouse e Friends 1500 Peças! Excelente passatempo para toda a família!!!!!",
          "manufacturer": "Toyster",
          "brand": "Classic",
          "character": "Mickey",
          "material": "cartão",
          "weight": 0,
          "height": 99,
          "width": 30,
          "depth": 0,
          "fullPrice": 129.99
        },
        {
          "id": 25,
          "name": "Pipoqueira elétrica Mallory Mickey com Ar quente Verm 1200W 127V",
          "slug": "pipoqueira-eletrica-mallory-mickey-com-ar-quente-vermelho-1200w-127v",
          "title": "Pipoqueira elétrica Mickey Vermelho 127V",
          "category": "Classicos",
          "department": "Eletrodomésticos",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Com sua Mallory Mickey Mouse você estará pronto para desfrutar plenamente de suas séries e filmes favoritos, como se estivesse no cinema. Explosão de sabor. Seu desenho especial tornará sua cozinha num lugar alegre e divertido. Delicie-se com algumas deliciosas pipocas, carregadas com toda a magia da Disney.",
          "manufacturer": "Mallory",
          "brand": "Classic",
          "character": "Mickey",
          "material": "metal",
          "weight": 0,
          "height": 26.5,
          "width": 0,
          "depth": 0,
          "fullPrice": 124.9
        },
        {
          "id": 26,
          "name": "Tablet Multilaser M7 Minnie NB368 7' 32GB preto e 1GB de memória RAM",
          "slug": "tablet-multi-m7-minnie-nb368-7pol-32gb-preto-1gb-de-memoria-ram",
          "title": "Tablet Multi 7pol 32GB 1GB RAM Preto",
          "category": "Classicos",
          "department": "Eletrônicos",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Este tablet é ideal para cada uma de suas atividades: editar fotos, documentos, navegar na web e muito mais! Seu design fino, compacto e portátil é a combinação perfeita de desempenho e versatilidade. Transferir, sincronizar e acessar aos seus dispositivos quantas vezes quiser agora é possivel. Suas conexões wi-fi, bluetooth, usb-c permitem que você maximize suas funções.",
          "manufacturer": "Multi",
          "brand": "Classic",
          "character": "Minnie",
          "material": "plástico",
          "weight": 0.75,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 434
        },
        {
          "id": 27,
          "name": "Kit 2 Copos Colors Bico De Silicone Disney Minnie Rosa Lillo",
          "slug": "kit-2-copos-colors-bico-de-silicone-disney-minnie-rosa-lillo",
          "title": "Kit 2 Copos Colors Bico Silicone Minnie Rosa Lillo",
          "category": "Classicos",
          "department": "Eletrônicos",
          "productionBanner": "/images/banners/classic/banner-classic-image1-minnieWithMickey.png",
          "description": "Tempos de muitas descobertas e alegrias estão por começar, e nada melhor do que estar preparado para estar junto neste ciclo de desenvolvimento. O Kit com 2 Copos Colors da Lillo (300ml) foi desenvolvido especialmente para permitir que a fase de transição da mamadeira para o copo ocorra de forma mais tranquila. Cada copo possui um tipo de bebedor diferente para acompanhar o desenvolvimento da criança: 6+ Meses e 12+ Meses. O Bebedor de silicone é macio e flexível recomendado para os pequenos com 6+ Meses .O bebedor em TPE é confortável e resistente recomendado para crianças com 12+ Meses. Os dois formatos de bebedor possibilitam o contato agradável com a boca da criança. Sua tampa tem fechamento em sistema click eficaz permitindo o fácil armazenamento e uso durante passeios. Livre de BPA.",
          "manufacturer": "Lillo",
          "brand": "Classic",
          "character": "Minnie",
          "material": "plástico",
          "weight": 0,
          "height": 0,
          "width": 0,
          "depth": 0,
          "fullPrice": 49.99
        },
        {
          "id": 28,
          "name": "Cadeira PcGamer Ergonômica Giratória Braço 3d Marvel",
          "slug": "cadeira-pcGamer-ergonomica-gaming-giratoria-braco-3d-marvel",
          "title": "Cadeira Gamer Giratoria Braço 3d Marvel",
          "category": "Marvel",
          "department": "Decoração",
          "productionBanner": "/images/banners/marvel/banner-marvel-image1-heroesTogether.png",
          "description": "Bem Vindo a Cadeiras Inc. Cadeira De Game Gamer Jogar Videogame Escritorio Presidente Giratória Com Ajuste de Altura Com Rodinhas Tipo Gamer Barata Com Braço Regulável 3D Marvel Pro Giratória Reclinável Para 150Kg. Proteja o mundo contra ameaças catastrófica e tenha uma excelente performance gamer sem abrir mão do conforto com a Cadeira Gamer Marvel Capitão América Reclinável Gaming Pro. Design Ousado e Moderno. Construída com espuma injetada e PU, essa Cadeira para Jogos possui um design e estampa inspirados em um dos super heróis mais populares da Disney, o Capitão América. E foi projetada para trazer um layout ousado e moderno para seu espaço de jogos. Maior Resistência e Durabilidade. Por ser revestida com tecido resistente e apresentar uma estrutura em metal, a Cadeira Gamer EagleX oferece muito mais resistência e durabilidade. Com ela, seus movimentos terão a firmeza e precisão necessários para encarar qualquer vilão e sair vitorioso(a) em muitas batalhas. Conforto Extra. A Cadeira Gamer EagleX Capitão América possui apoio de braço ajustável, assim como almofadas lombar e cervical removível, além de Sistema Relax que posiciona a Cadeira no melhor ângulo, para garantir partidas muito mais agradáveis, com total conforto e praticidade. Mobilidade que faz a diferença! Destaque ainda para seu sistema de rotação 360° e 5 rodízios que conferem a mobilidade necessária para um desempenho de alto nível. Adequado para mesa gamer que possuem 20cm entre assento da cadeira e o tampo da mesa de escritório. Diferenciais:",
          "manufacturer": "BabaShop",
          "brand": "Marvel",
          "character": "Capitão América",
          "material": "espuma",
          "weight": 16,
          "height": 99,
          "width": 68,
          "depth": 65,
          "fullPrice": 1350.90
        }
      ], {});

  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('product', null, {});
  }
};
